import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import PrimaryButton from '../../components/PrimaryButton';
import SecondaryButton from '../../components/SecondaryButton';
import ScreenContainer from '../../components/ScreenContainer';
import { colors, radius, spacing, typography } from '../../theme';

export default function LoginScreen({ navigation }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const goToRole = (role) => navigation.replace(role === 'admin' ? 'AdminFlow' : 'InstallerFlow');
  return <ScreenContainer style={styles.screen}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.brandArea}><View style={styles.logo}><Text style={styles.logoText}>TI</Text></View><Text style={styles.title}>TrackInstall</Text><Text style={styles.subtitle}>Installer Visit Management System</Text></View><View style={styles.form}><Text style={styles.label}>Email</Text><TextInput value={email} onChangeText={setEmail} placeholder="Enter your email" placeholderTextColor={colors.textSecondary} autoCapitalize="none" autoComplete="email" keyboardType="email-address" style={styles.input} /><Text style={styles.label}>Password</Text><TextInput value={password} onChangeText={setPassword} placeholder="Enter your password" placeholderTextColor={colors.textSecondary} secureTextEntry autoComplete="password" style={styles.input} /><PrimaryButton title="Login" onPress={() => {}} /></View><View style={styles.demoSection}><View style={styles.dividerRow}><View style={styles.divider} /><Text style={styles.dividerText}>Demo Login</Text><View style={styles.divider} /></View><Text style={styles.demoDescription}>Explore the prototype using a demo role.</Text><SecondaryButton title="Continue as Admin" onPress={() => goToRole('admin')} /><SecondaryButton title="Continue as Installer" onPress={() => goToRole('installer')} style={styles.secondDemoButton} /></View><View style={styles.mode}><View style={styles.modeDot} /><Text style={styles.modeText}>Demo Mode</Text></View></ScrollView></KeyboardAvoidingView></ScreenContainer>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: spacing.lg }, flex: { flex: 1 }, content: { flexGrow: 1, paddingVertical: spacing.xxl }, brandArea: { alignItems: 'center', marginTop: spacing.lg, marginBottom: spacing.xxl }, logo: { width: 64, height: 64, borderRadius: radius.lg, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md }, logoText: { ...typography.heading, color: colors.white }, title: { ...typography.display, color: colors.text }, subtitle: { ...typography.body, color: colors.textSecondary, marginTop: spacing.xs, textAlign: 'center' }, form: { gap: spacing.sm }, label: { ...typography.label, color: colors.text, marginTop: spacing.sm }, input: { height: 52, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, paddingHorizontal: spacing.md, color: colors.text, ...typography.body }, demoSection: { marginTop: spacing.xxl }, dividerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, divider: { flex: 1, height: 1, backgroundColor: colors.border }, dividerText: { ...typography.label, color: colors.textSecondary }, demoDescription: { ...typography.body, color: colors.textSecondary, textAlign: 'center', marginVertical: spacing.md }, secondDemoButton: { marginTop: spacing.sm }, mode: { marginTop: 'auto', alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingTop: spacing.xxl }, modeDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.success }, modeText: { ...typography.caption, color: colors.textSecondary } });
