import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, radius, spacing, typography } from '../theme';
export function StatusBadge({ status }) { const tone = status?.includes('PENDING') ? '#B45309' : status === 'REJECTED' || status === 'INACTIVE' ? '#B42318' : status === 'PAID' || status === 'COMPLETED' || status === 'APPROVED' || status === 'ACTIVE' ? '#18794E' : colors.primary; return <View style={[styles.badge, { backgroundColor: `${tone}18` }]}><Text style={[styles.badgeText, { color: tone }]}>{status?.replaceAll('_', ' ')}</Text></View>; }
export function SearchBar({ value, onChangeText, placeholder = 'Search' }) { return <TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.textSecondary} style={styles.search} />; }
export function FilterChips({ options, selected, onSelect }) { return <View style={styles.chips}>{options.map((option) => <Pressable key={option} onPress={() => onSelect(option)} style={[styles.chip, selected === option && styles.chipActive]}><Text style={[styles.chipText, selected === option && styles.chipTextActive]}>{option}</Text></Pressable>)}</View>; }
export function SectionHeader({ title, action, onPress }) { return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{action ? <Pressable onPress={onPress}><Text style={styles.action}>{action}</Text></Pressable> : null}</View>; }
export function EmptyState({ text }) { return <View style={styles.empty}><Text style={styles.emptyText}>{text}</Text></View>; }
export const adminStyles = StyleSheet.create({ page: { paddingBottom: spacing.xl }, title: { ...typography.title, color: colors.text, marginTop: spacing.sm }, subtitle: { ...typography.body, color: colors.textSecondary, marginTop: spacing.xs }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, marginTop: spacing.md }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, meta: { ...typography.caption, color: colors.textSecondary, marginTop: spacing.xs }, cardTitle: { ...typography.heading, color: colors.text }, sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.xl, marginBottom: spacing.sm }, sectionTitle: { ...typography.heading, color: colors.text }, action: { ...typography.label, color: colors.primary }, badge: { borderRadius: radius.pill, paddingVertical: 3, paddingHorizontal: spacing.sm }, badgeText: { fontSize: 11, fontWeight: '700' }, search: { height: 48, marginTop: spacing.md, paddingHorizontal: spacing.md, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, color: colors.text }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md }, chip: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.pill, paddingHorizontal: 12, paddingVertical: 7 }, chipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { ...typography.caption, color: colors.textSecondary }, chipTextActive: { color: colors.white }, empty: { alignItems: 'center', padding: spacing.xl, backgroundColor: colors.surface, borderRadius: radius.md, marginTop: spacing.md }, emptyText: { ...typography.body, color: colors.textSecondary, textAlign: 'center' } });
const styles = adminStyles;
